language: ruby
rvm:
  - 2.4.0
  - 2.7.0

before_install:
  # https://github.com/danmayer/coverband/issues/162#issuecomment-452173268
  - rm /home/travis/.rvm/gems/*/specifications/bundler-2.*.gemspec || true
  - gem install bundler -v '<2'
